import { Professional, ProfessionalStats } from "./professionalsTypes";

export const professionalsMockData: Professional[] = [
  {
    id: 1,
    name: "Maria Silva",
    email: "maria.silva@unclic.com",
    phone: "(11) 99999-1111",
    specialties: [
      "Corte Feminino",
      "Coloração",
      "Hidratação",
      "Escova Progressiva",
    ],
    status: "ativo",
    commission: 45,
    workDays: [
      "monday",
      "tuesday",
      "wednesday",
      "thursday",
      "friday",
      "saturday",
    ],
    workHours: {
      start: "08:00",
      end: "18:00",
    },
    hiredDate: new Date(2022, 2, 15),
    rating: 4.9,
    totalServices: 1247,
    totalRevenue: 89650.0,
    completedServices: 1189,
    cancelledServices: 58,
    bio: "Especialista em coloração e tratamentos capilares com mais de 8 anos de experiência. Apaixonada por transformar o visual das clientes.",
    experience: 8,
    certifications: [
      "Certificação L'Oréal Professional",
      "Curso de Colorimetria Avançada",
      "Especialização em Química Capilar",
    ],
    isOwner: true,
  },
  {
    id: 2,
    name: "João Santos",
    email: "joao.santos@unclic.com",
    phone: "(11) 88888-2222",
    specialties: ["Corte Masculino", "Barba", "Bigode"],
    status: "ativo",
    commission: 40,
    workDays: ["tuesday", "wednesday", "thursday", "friday", "saturday"],
    workHours: {
      start: "09:00",
      end: "19:00",
    },
    hiredDate: new Date(2022, 8, 10),
    rating: 4.7,
    totalServices: 892,
    totalRevenue: 31220.0,
    completedServices: 856,
    cancelledServices: 36,
    bio: "Barbeiro tradicional com técnicas modernas. Especialista em cortes masculinos clássicos e contemporâneos.",
    experience: 6,
    certifications: [
      "Curso de Barbearia Clássica",
      "Certificação em Técnicas de Corte Masculino",
    ],
  },
  {
    id: 3,
    name: "Ana Costa",
    email: "ana.costa@unclic.com",
    phone: "(11) 77777-3333",
    specialties: ["Manicure", "Pedicure", "Alongamento de Unhas", "Nail Art"],
    status: "ativo",
    commission: 35,
    workDays: ["monday", "tuesday", "thursday", "friday", "saturday"],
    workHours: {
      start: "08:30",
      end: "17:30",
    },
    hiredDate: new Date(2023, 0, 20),
    rating: 4.8,
    totalServices: 1156,
    totalRevenue: 34680.0,
    completedServices: 1098,
    cancelledServices: 58,
    bio: "Nail designer com especialização em nail art e técnicas de alongamento. Sempre atualizada com as últimas tendências.",
    experience: 4,
    certifications: [
      "Curso de Nail Art Profissional",
      "Certificação em Alongamento de Unhas",
      "Workshop de Técnicas Europeias",
    ],
  },
  {
    id: 4,
    name: "Carla Souza",
    email: "carla.souza@unclic.com",
    phone: "(11) 66666-4444",
    specialties: [
      "Sobrancelha",
      "Maquiagem",
      "Limpeza de Pele",
      "Design de Sobrancelha",
    ],
    status: "ativo",
    commission: 38,
    workDays: ["wednesday", "thursday", "friday", "saturday"],
    workHours: {
      start: "10:00",
      end: "19:00",
    },
    hiredDate: new Date(2023, 4, 5),
    rating: 4.9,
    totalServices: 645,
    totalRevenue: 29025.0,
    completedServices: 618,
    cancelledServices: 27,
    bio: "Especialista em design de sobrancelhas e maquiagem profissional. Formada em estética com foco em harmonização facial.",
    experience: 5,
    certifications: [
      "Formação em Estética",
      "Curso de Design de Sobrancelhas",
      "Certificação em Maquiagem Profissional",
      "Workshop de Harmonização Facial",
    ],
  },
  {
    id: 5,
    name: "Pedro Oliveira",
    email: "pedro.oliveira@unclic.com",
    phone: "(11) 55555-5555",
    specialties: ["Corte Masculino", "Corte Feminino", "Hidratação"],
    status: "ferias",
    commission: 42,
    workDays: ["monday", "tuesday", "wednesday", "friday", "saturday"],
    workHours: {
      start: "09:00",
      end: "18:00",
    },
    hiredDate: new Date(2023, 6, 12),
    rating: 4.6,
    totalServices: 234,
    totalRevenue: 12870.0,
    completedServices: 221,
    cancelledServices: 13,
    bio: "Profissional versátil com experiência tanto em cortes masculinos quanto femininos. Apaixonado por técnicas de hidratação capilar.",
    experience: 3,
    certifications: [
      "Curso de Cabeleireiro Unissex",
      "Certificação em Tratamentos Capilares",
    ],
  },
  {
    id: 6,
    name: "Lucia Fernandes",
    email: "lucia.fernandes@unclic.com",
    phone: "(11) 44444-6666",
    specialties: ["Massagem", "Limpeza de Pele", "Hidratação Facial"],
    status: "inativo",
    commission: 40,
    workDays: ["monday", "wednesday", "friday"],
    workHours: {
      start: "09:00",
      end: "16:00",
    },
    hiredDate: new Date(2022, 10, 8),
    rating: 4.5,
    totalServices: 178,
    totalRevenue: 8900.0,
    completedServices: 165,
    cancelledServices: 13,
    bio: "Esteticista com foco em bem-estar e relaxamento. Especializada em massagens terapêuticas e cuidados faciais.",
    experience: 7,
    certifications: [
      "Formação em Estética",
      "Curso de Massagem Terapêutica",
      "Certificação em Cuidados Faciais",
    ],
  },
];

export const professionalStats: ProfessionalStats = {
  totalProfessionals: professionalsMockData.length,
  activeProfessionals: professionalsMockData.filter((p) => p.status === "ativo")
    .length,
  totalRevenue: professionalsMockData.reduce(
    (acc, p) => acc + p.totalRevenue,
    0,
  ),
  averageRating:
    professionalsMockData.reduce((acc, p) => acc + p.rating, 0) /
    professionalsMockData.length,
  totalServices: professionalsMockData.reduce(
    (acc, p) => acc + p.totalServices,
    0,
  ),
  averageCommission:
    professionalsMockData.reduce((acc, p) => acc + p.commission, 0) /
    professionalsMockData.length,
};

export const workDaysOptions = [
  { id: "monday", name: "Segunda-feira", short: "Seg" },
  { id: "tuesday", name: "Terça-feira", short: "Ter" },
  { id: "wednesday", name: "Quarta-feira", short: "Qua" },
  { id: "thursday", name: "Quinta-feira", short: "Qui" },
  { id: "friday", name: "Sexta-feira", short: "Sex" },
  { id: "saturday", name: "Sábado", short: "Sáb" },
  { id: "sunday", name: "Domingo", short: "Dom" },
];

export const availableSpecialties = [
  "Corte Feminino",
  "Corte Masculino",
  "Coloração",
  "Hidratação",
  "Escova Progressiva",
  "Barba",
  "Bigode",
  "Manicure",
  "Pedicure",
  "Alongamento de Unhas",
  "Nail Art",
  "Sobrancelha",
  "Design de Sobrancelha",
  "Maquiagem",
  "Limpeza de Pele",
  "Massagem",
  "Hidratação Facial",
];
