import { Service, ServiceCategory, ServiceStats } from "./servicesTypes";

export const servicesMockData: Service[] = [
  {
    id: 1,
    name: "Corte Feminino",
    description: "Corte moderno e personalizado para mulheres",
    category: "cabelo-feminino",
    price: 60.0,
    duration: 60,
    commission: 40,
    isActive: true,
    popularity: 145,
    averageRating: 4.8,
    professionals: ["Maria Silva", "Ana Costa"],
    createdAt: new Date(2023, 0, 15),
    updatedAt: new Date(2024, 0, 20),
  },
  {
    id: 2,
    name: "Corte Masculino",
    description: "Corte masculino tradicional e moderno",
    category: "cabelo-masculino",
    price: 35.0,
    duration: 45,
    commission: 35,
    isActive: true,
    popularity: 98,
    averageRating: 4.6,
    professionals: ["João Santos"],
    createdAt: new Date(2023, 0, 15),
    updatedAt: new Date(2024, 0, 18),
  },
  {
    id: 3,
    name: "Escova Progressiva",
    description: "Alisamento natural com escova progressiva",
    category: "cabelo-feminino",
    price: 120.0,
    duration: 180,
    commission: 45,
    isActive: true,
    popularity: 67,
    averageRating: 4.9,
    professionals: ["Maria Silva"],
    createdAt: new Date(2023, 1, 10),
    updatedAt: new Date(2024, 0, 15),
  },
  {
    id: 4,
    name: "Manicure",
    description: "Cuidado completo das unhas das mãos",
    category: "unhas",
    price: 25.0,
    duration: 45,
    commission: 30,
    isActive: true,
    popularity: 189,
    averageRating: 4.7,
    professionals: ["Ana Costa", "Carla Souza"],
    createdAt: new Date(2023, 0, 15),
    updatedAt: new Date(2024, 0, 22),
  },
  {
    id: 5,
    name: "Pedicure",
    description: "Cuidado completo das unhas dos pés",
    category: "unhas",
    price: 30.0,
    duration: 60,
    commission: 30,
    isActive: true,
    popularity: 156,
    averageRating: 4.8,
    professionals: ["Ana Costa", "Carla Souza"],
    createdAt: new Date(2023, 0, 15),
    updatedAt: new Date(2024, 0, 19),
  },
  {
    id: 6,
    name: "Alongamento de Unhas",
    description: "Alongamento com gel ou fibra de vidro",
    category: "unhas",
    price: 45.0,
    duration: 90,
    commission: 35,
    isActive: true,
    popularity: 89,
    averageRating: 4.9,
    professionals: ["Ana Costa"],
    createdAt: new Date(2023, 2, 5),
    updatedAt: new Date(2024, 0, 10),
  },
  {
    id: 7,
    name: "Hidratação Capilar",
    description: "Tratamento profundo para cabelos ressecados",
    category: "tratamentos",
    price: 50.0,
    duration: 90,
    commission: 40,
    isActive: true,
    popularity: 134,
    averageRating: 4.8,
    professionals: ["Maria Silva", "Ana Costa"],
    createdAt: new Date(2023, 1, 20),
    updatedAt: new Date(2024, 0, 12),
  },
  {
    id: 8,
    name: "Coloração",
    description: "Tintura e coloração profissional",
    category: "cabelo-feminino",
    price: 80.0,
    duration: 120,
    commission: 45,
    isActive: true,
    popularity: 112,
    averageRating: 4.7,
    professionals: ["Maria Silva"],
    createdAt: new Date(2023, 1, 25),
    updatedAt: new Date(2024, 0, 8),
  },
  {
    id: 9,
    name: "Barba",
    description: "Aparar e modelar barba",
    category: "cabelo-masculino",
    price: 25.0,
    duration: 30,
    commission: 35,
    isActive: true,
    popularity: 203,
    averageRating: 4.6,
    professionals: ["João Santos"],
    createdAt: new Date(2023, 0, 15),
    updatedAt: new Date(2024, 0, 25),
  },
  {
    id: 10,
    name: "Sobrancelha",
    description: "Design e modelagem de sobrancelhas",
    category: "estetica",
    price: 20.0,
    duration: 30,
    commission: 30,
    isActive: true,
    popularity: 178,
    averageRating: 4.8,
    professionals: ["Ana Costa", "Carla Souza"],
    createdAt: new Date(2023, 0, 15),
    updatedAt: new Date(2024, 0, 16),
  },
  {
    id: 11,
    name: "Maquiagem",
    description: "Maquiagem profissional para eventos",
    category: "estetica",
    price: 60.0,
    duration: 60,
    commission: 40,
    isActive: true,
    popularity: 95,
    averageRating: 4.9,
    professionals: ["Carla Souza"],
    createdAt: new Date(2023, 2, 10),
    updatedAt: new Date(2024, 0, 14),
  },
  {
    id: 12,
    name: "Limpeza de Pele",
    description: "Limpeza facial profunda e revitalizante",
    category: "estetica",
    price: 45.0,
    duration: 75,
    commission: 35,
    isActive: false,
    popularity: 67,
    averageRating: 4.7,
    professionals: ["Carla Souza"],
    createdAt: new Date(2023, 3, 5),
    updatedAt: new Date(2023, 11, 15),
  },
];

export const serviceCategories: ServiceCategory[] = [
  {
    id: "cabelo-feminino",
    name: "Cabelo Feminino",
    description: "Serviços capilares para mulheres",
    services: 3,
    color: "bg-pink-500",
  },
  {
    id: "cabelo-masculino",
    name: "Cabelo Masculino",
    description: "Serviços capilares para homens",
    services: 2,
    color: "bg-blue-500",
  },
  {
    id: "unhas",
    name: "Unhas",
    description: "Serviços de manicure e pedicure",
    services: 3,
    color: "bg-purple-500",
  },
  {
    id: "tratamentos",
    name: "Tratamentos",
    description: "Tratamentos capilares especiais",
    services: 1,
    color: "bg-green-500",
  },
  {
    id: "estetica",
    name: "Estética",
    description: "Serviços de beleza e estética",
    services: 3,
    color: "bg-orange-500",
  },
];

export const serviceStats: ServiceStats = {
  totalServices: servicesMockData.length,
  activeServices: servicesMockData.filter((s) => s.isActive).length,
  totalRevenue: servicesMockData.reduce(
    (acc, service) => acc + service.price * service.popularity,
    0,
  ),
  averagePrice:
    servicesMockData.reduce((acc, service) => acc + service.price, 0) /
    servicesMockData.length,
  mostPopularService: servicesMockData.reduce((prev, current) =>
    prev.popularity > current.popularity ? prev : current,
  ).name,
  categoriesCount: serviceCategories.length,
};

export const professionals = [
  {
    id: 1,
    name: "Maria Silva",
    specialties: ["Corte Feminino", "Coloração", "Hidratação"],
  },
  {
    id: 2,
    name: "João Santos",
    specialties: ["Corte Masculino", "Barba"],
  },
  {
    id: 3,
    name: "Ana Costa",
    specialties: ["Manicure", "Pedicure", "Sobrancelha"],
  },
  {
    id: 4,
    name: "Carla Souza",
    specialties: ["Estética", "Maquiagem", "Limpeza de Pele"],
  },
];
